// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Area: typeof import("./src/components/editor/Area.vue")["default"];
    Arrangement: typeof import("./src/components/LowCodeCompoent/Attrs/Arrangement.vue")["default"];
    Attr: typeof import("./src/components/editor/Attr.vue")["default"];
    Background: typeof import("./src/components/LowCodeCompoent/Attrs/Background.vue")["default"];
    Border: typeof import("./src/components/LowCodeCompoent/Attrs/Border.vue")["default"];
    ComponentLayer: typeof import("./src/components/componentLayer.vue")["default"];
    ComponentList: typeof import("./src/components/componentList.vue")["default"];
    copy: typeof import("./src/components/LowCodeCompoent/Attrs/TextHorizontalAlign copy.vue")["default"];
    DefaultAttr: typeof import("./src/components/defaultAttr.vue")["default"];
    Editor: typeof import("./src/components/editor/index.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCollapse: typeof import("element-plus/es")["ElCollapse"];
    ElCollapseItem: typeof import("element-plus/es")["ElCollapseItem"];
    ElColorPick: typeof import("element-plus/es")["ElColorPick"];
    ElColorPicker: typeof import("element-plus/es")["ElColorPicker"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSlider: typeof import("element-plus/es")["ElSlider"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    Grid: typeof import("./src/components/editor/Grid.vue")["default"];
    Header: typeof import("./src/components/header.vue")["default"];
    MarkLine: typeof import("./src/components/editor/MarkLine.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Shadow: typeof import("./src/components/LowCodeCompoent/Attrs/Shadow.vue")["default"];
    Shape: typeof import("./src/components/editor/Shape.vue")["default"];
    Text: typeof import("./src/components/LowCodeCompoent/Attrs/Text.vue")["default"];
    TextAlign: typeof import("./src/components/LowCodeCompoent/Attrs/TextAlign.vue")["default"];
    TextHorizontalAlign: typeof import("./src/components/LowCodeCompoent/Attrs/TextHorizontalAlign.vue")["default"];
    TextValue: typeof import("./src/components/LowCodeCompoent/Attrs/TextValue.vue")["default"];
    TextVerticalAlign: typeof import("./src/components/LowCodeCompoent/Attrs/TextVerticalAlign.vue")["default"];
    VButton: typeof import("./src/components/LowCodeCompoent/VButton/index.vue")["default"];
    VGroup: typeof import("./src/components/LowCodeCompoent/VGroup/index.vue")["default"];
    VPicture: typeof import("./src/components/LowCodeCompoent/VPicture/index.vue")["default"];
  }
}
