// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Area: typeof import('./src/components/editor/Area.vue')['default']
    ComponentLayer: typeof import('./src/components/componentLayer.vue')['default']
    ComponentList: typeof import('./src/components/componentList.vue')['default']
    Editor: typeof import('./src/components/editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Grid: typeof import('./src/components/editor/Grid.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    MarkLine: typeof import('./src/components/editor/MarkLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shape: typeof import('./src/components/editor/Shape.vue')['default']
    VButton: typeof import('./src/components/LowCodeCompoent/VButton/index.vue')['default']
    VGroup: typeof import('./src/components/LowCodeCompoent/VGroup/index.vue')['default']
    VPicture: typeof import('./src/components/LowCodeCompoent/VPicture/index.vue')['default']
  }
}
